"""add project_members

Revision ID: fa360b422160
Revises: 3a08d747ad9e
Create Date: 2026-10-07 14:04:50.043881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa360b422160'
down_revision: Union[str, Sequence[str], None] = '3a08d747ad9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('idx_project_members_user_id'), table_name='project_members')
    op.create_index('ix_project_members_user_id', 'project_members', ['user_id'], unique=False)
    op.drop_index(op.f('idx_projects_owner_id'), table_name='projects')
    op.alter_column('tasks', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('idx_tasks_assignee_id'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_status'), table_name='tasks')
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.create_index(op.f('idx_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('idx_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('idx_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('idx_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.alter_column('tasks', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('idx_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.drop_index('ix_project_members_user_id', table_name='project_members')
    op.create_index(op.f('idx_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.drop_column('project_members', 'created_at')
    # ### end Alembic commands ###
